### ISSUE TITLE
”go get -x github.com/sciter-sdk/go-sciter“ is error in “cgo”

### ISSUE THREAD

**Issue by xiaonaoer** [sciter-sdk/go-sciter#246] opened 2020-08-19 02:31 UTC
Hello, I have encountered the following error:

```
/usr/lib/go/pkg/tool/linux_amd64/compile -o $WORK/b001/_pkg_.a -trimpath "$WORK/b001=>" -p github.com/sciter-sdk/go-sciter -buildid 1Kajp57NcmyFvaNCGAVK/1Kajp57NcmyFvaNCGAVK -goversion go1.15 -D "" -importcfg $WORK/b001/importcfg -pack -c=4 ./generate.go ./types_string.go ./value.go ./wrapper.go $WORK/b001/_cgo_gotypes.go $WORK/b001/sciter.cgo1.go $WORK/b001/sciter_linux.cgo1.go $WORK/b001/types.cgo1.go $WORK/b001/utils.cgo1.go $WORK/b001/_cgo_import.go
# github.com/sciter-sdk/go-sciter
go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter.go:1025:142: cannot use _cgo1 (type *_Ctype_HWINDOW) as type **_Ctype_struct__GtkWidget in argument to _Cfunc_SciterGetElementHwnd

```
> 
![微信图片_20200819140212](https://user-images.githubusercontent.com/11326721/90597959-b749f980-e224-11ea-8b50-427521599f4f.png)

go version:
```
go version go1.15 linux/amd64
```

**Comment by pravic** [comment] 2020-08-20 03:05
Duplicate of #245

**Closed by pravic** 2020-08-20 03:05 UTC
Labels: r:duplicate
