### ISSUE TITLE
Panic when creating window in goroutine

### ISSUE THREAD

**Issue by ilya-fedin** [sciter-sdk/go-sciter#135] opened 2018-04-18 19:53 UTC
https://pastebin.com/B1yvXvzv

**Comment by pravic** [comment] 2018-04-19 04:06
Apparently,  window creation must be done from the main thread only. I'll close this in favor of #133.

**Comment by ilya-fedin** [comment] 2018-04-19 04:27
But I need to open the window when selecting an item in the tray icon menu (https://github.com/getlantern/systray). How can I do it?

**Comment by pravic** [comment] 2018-04-19 04:49
Sorry, I haven't noticed that that issue was created by a different author.

Well, this is tricky. Ideally,  Sciter supported tray out of box. As for now.. I suggest to pass the "window creation message" via a script to guarantee that it will be executed in the main thread.

**Comment by ilya-fedin** [comment] 2018-04-19 05:08
What script do you mean? Bash script?

**Comment by pravic** [comment] 2018-04-19 13:46
I meant Sciter script. But no, I was wrong.

I have checked how systray (and other similar libraries) work. Each of them has its own message loop that blocks the caller's thread. So does Sciter. So it is impossible to have two message loops within the same thread.

Although on Windows you can run another message loop in a separate thread, but you can't do that on Linux or OSX.


<details>
  <summary>Here is an example of how it just works</summary>

```go
package main

import (
	"log"
	"syscall"

	"github.com/sciter-sdk/go-sciter"
	"github.com/sciter-sdk/go-sciter/window"
	"github.com/getlantern/systray"
	"github.com/getlantern/systray/example/icon"
	"github.com/lxn/win"
)

func main() {
	Trace("main")
	systray.Run(onReady, onExit)
	Trace("eof")
}

func onReady() {
	Trace("onReady")
	systray.SetIcon(icon.Data)
	systray.SetTitle("Tray example")
	systray.SetTooltip("Pretty awesome tray")

	mCreate := systray.AddMenuItem("Create", "")
	go func() {
		<- mCreate.ClickedCh
		Trace("Create")

		w, _ := window.New(sciter.SW_TITLEBAR|sciter.SW_RESIZEABLE|sciter.SW_CONTROLS|sciter.SW_MAIN|sciter.SW_ENABLE_DEBUG, nil)
		w.LoadFile("simple.html")
		w.SetTitle("Tray Example")
		w.Show()
		w.Run()

		Trace("Closed window")
	}()

	mQuit := systray.AddMenuItem("Quit", "")
	go func() {
		<- mQuit.ClickedCh
		Trace("Quit")
		systray.Quit()
	}()
}

func onExit() {
	Trace("Bye")
}

var GetCurrentThreadId uintptr

func init() {
	dll := win.MustLoadLibrary("kernel32.dll")
	GetCurrentThreadId = win.MustGetProcAddress(dll, "GetCurrentThreadId")
}

func getId() uint32 {
	ret, _, _ := syscall.Syscall(GetCurrentThreadId, 0, 0, 0, 0)
	return uint32(ret)
}

func Trace(msg string) {
	log.Printf("[%04d] %s", getId(), msg)
}
```
</details>
.

But I didn't manage to create a new window again after the first one was closed.

**Comment by ilya-fedin** [comment] 2018-04-20 06:39
Ok, I made the settings window as a separate application. It's a bit of a crutch, but it works. It remains to understand why in the header of the window there are superfluous symbols.
![screenshot_20180420_103908](https://user-images.githubusercontent.com/17829319/39034341-184816a6-4487-11e8-8f83-3a50bd4d442d.png)

**Comment by pravic** [comment] 2018-04-20 09:07
What OS?

**Comment by ilya-fedin** [comment] 2018-04-20 09:09
Linux. On Windows this does not work, I had to do this:
```
if runtime.GOOS == "linux" {
	w.SetTitle("Settings\x00")
} else {
	w.SetTitle("Settings")
}
```

**Comment by pravic** [comment] 2018-04-20 09:16
Thanks, I'll check it soon.

**Comment by pravic** [comment] 2018-04-20 12:53
@ilya-fedin  I could not reproduce it, but anyway - try current master.

**Comment by ilya-fedin** [comment] 2018-04-20 19:52
Yes, it works. Thank you.

**Closed** 2018-04-20 19:59 UTC
Labels: bug, r:wontfix, sciter-engine
